Abolish strenght strength
Abolish widht width
Abolish beleive believe
Abolish upate update
Abolish sefl self
Abolish interrup interrupt
Abolish lastest latest
Abolish previsou previous
Abolish chagne change
