hash -d dots="/home/marcel/.dotfiles"
hash -d weekly="/home/marcel/Nextcloud/Waterloo/QuIN Lab/Weekly report"
hash -d ece657="/home/marcel/Nextcloud/Waterloo/Courses/2021A/ECE657A: Data and Knowledge Modeling and Analysis"
hash -d quin="/home/marcel/Nextcloud/Waterloo/QuIN Lab"
hash -d cmos="/home/marcel/code/quin/CMOS RTN"
