hash -d dots="/home/marcel/.dotfiles"
hash -d weekly="/home/marcel/Nextcloud/Waterloo/QuIN_Lab/Weekly report"
hash -d ece657="/home/marcel/Nextcloud/Waterloo/Courses/2021A/ECE657A_Data_and_Knowledge_Modeling_and_Analysis"
hash -d quin="/home/marcel/Nextcloud/Waterloo/QuIN_Lab"
hash -d cmos="/home/marcel/code/quin/CMOS_RTN"
