hash -d dots="/home/marcel/.dotfiles"
hash -d weekly="/home/marcel/Nextcloud/Waterloo/QuIN_Lab/Weekly report"
hash -d ece650="/home/marcel/Nextcloud/Waterloo/Courses/2021C/ECE 650 - Methods & Tools for Software Eng/"
hash -d quin="/home/marcel/Nextcloud/Waterloo/QuIN_Lab"
hash -d cmos="/home/marcel/code/quin/CMOS_RTN"
