#! /bin/sh

source ~/.dotfiles/omzsh/exports.sh

pkill sxhkd; sxhkd &

#bspc monitor -d $(seq -s ' ' 0 9)
bspc monitor eDP1 -d 0 1 2 3 4
bspc monitor HDMI2 -d 5 6 7 8 9

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52

bspc rule -a Oblogout state=floating


#
# Startup scripts
#

# >>> Cycle wallpapers
pkill wallpaper-timer; wallpaper-timer &
# <<<

# >>> Lemonbar
pkill top.sh; ~/.dotfiles/lemonbar/top.sh &
pkill bottom.sh; ~/.dotfiles/lemonbar/bottom.sh &
# <<<

# >>> Keybindings
xbindkeys &
doxmodmap
# <<<

pkill compton; compton -b --config ~/.config/compton/compton.conf &

pkill dunst; dunst &

pkill redshift
redshift 2>&1 > /dev/null || notify "Failed to start redshift\!" --urgent

forever stopall
NODE_ENV=production forever start ~/code/apollo/server.js &
# NODE_ENV=production forever start ~/code/PurpleRSS/index.js &

