"
" General settings
"

" Use space as leader
let mapleader = " "

" Indentation
set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

" Show (certain) invisibles
set listchars=space:·

" No need for vi compatability
set nocompatible

" Encoding and font
set encoding=utf-8
set guifont=Source\ Code\ Pro\ 12

" Line numbers
set number

" Syntax highlighting
syntax on

" Start scrolling 10 lines before the horizontal window border
set scrolloff=10

" Scroll with mousewheel
set mouse=a

" Allow buffers in background
set hidden


"
" Navigation
"

" Quick pane cycling
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Buffer cycling
nnoremap [[ :bp<CR>
nnoremap ]] :bn<CR>

" Go to most recent buffer
nnoremap <tab> :e #<CR>


"
" File handling
"

" CtrlP fuzzy finder
let g:ctrlp_show_hidden = 1
let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden --follow
  \ --ignore .git
  \ -g ""'

" Shortcut to close only current buffer
map <leader>q :bp<bar>sp<bar>bn<bar>bd<CR>


"
" Typing
"

function! RepeatChar(char, count)
  return repeat(a:char, a:count)
endfunction

" Insert character and go back to normal mode
nnoremap s :<C-U>exec "normal i".RepeatChar(nr2char(getchar()), v:count1)<CR>
nnoremap S :<C-U>exec "normal a".RepeatChar(nr2char(getchar()), v:count1)<CR>

if (&tildeop)
  nmap gcw guw~l
  nmap gcW guW~l
  nmap gciw guiw~l
  nmap gciW guiW~l
  nmap gcis guis~l
  nmap gc$ gu$~l
  nmap gcgc guu~l
  nmap gcc guu~l
  vmap gc gu~l
else
  nmap gcw guw~h
  nmap gcW guW~h
  nmap gciw guiw~h
  nmap gciW guiW~h
  nmap gcis guis~h
  nmap gc$ gu$~h
  nmap gcgc guu~h
  nmap gcc guu~h
  vmap gc gu~h
endif


"
" Plugins
"

call plug#begin('~/.vim/plugged')

" Tree view
Plug 'scrooloose/nerdtree'
" Plug 'Xuyuanp/nerdtree-git-plugin' " Commented until it's colours not icons

" Fuzzy file finder
Plug 'ctrlpvim/ctrlp.vim'

" Status bar
Plug 'vim-airline/vim-airline'

" Colourscheme
Plug 'dylanaraps/wal'

" Open files in last place
Plug 'farmergreg/vim-lastplace'

" File icons
Plug 'ryanoasis/vim-devicons'

" Indent guides
Plug 'Yggdroot/indentLine'

" Toggle comments
Plug 'scrooloose/nerdcommenter'

" Surround
Plug 'tpope/vim-surround'

" Emmet
Plug 'mattn/emmet-vim'

" Syntax plugins
Plug 'pangloss/vim-javascript'
Plug 'mustache/vim-mustache-handlebars'
Plug 'digitaltoad/vim-pug'

Plug 'vim-syntastic/syntastic'

call plug#end()

filetype plugin indent on


"
" Airline 
"

" Show by default
set laststatus=2

let g:airline#extensions#tabline#enabled = 1

" Use powerline fonts
let g:airline_powerline_fonts = 1

" Supposed to make leaving insert mode faster
set ttimeoutlen=50

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" Hide things that are broken with my fonts or that I don't like the look of
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.linenr = ''

" Hide default status bar
set shortmess+=F


"
" NERDTree
"

" Automatically open when starting vim on directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

" Close NERDTree if it's the only thing left
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Keybinding to open NERDTree
map <leader>n :NERDTreeToggle<CR>

" Show hidden files
let NERDTreeShowHidden=1

let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "",
    \ "Staged"    : "✚",
    \ "Untracked" : "",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : " ",
    \ "Dirty"     : "",
    \ "Clean"     : "",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }
let g:NERDTreeShowIgnoredStatus = 1

" Files to be hidden
let NERDTreeIgnore=['\.git$', '\.pioenvs$', '\.swp']

" Folders
let g:NERDTreeDirArrowExpandable = ''
let g:NERDTreeDirArrowCollapsible = ''
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1

" Use pretty icons
let g:WebDevIconsNerdTreeAfterGlyphPadding = '  '


"
" Wal
"

" Colourscheme settings
colorscheme wal


"
" Indent line
"

let g:indentLine_leadingSpaceEnabled = 1
let g:indentLine_leadingSpaceChar = '·'
let g:indentLine_bufNameExclude = ['_.*', 'NERD_tree.*']


"
" Emmet
"

let g:user_emmet_expandabbr_key = "<s-tab>"


"
" NERDCommenter
"

let g:NERDSpaceDelims = 1

map <C-_> <Plug>NERDCommenterToggle
imap <C-_> <Plug>NERDCommenterInsert


"
" CtrlP
"

let g:ctrlp_cmd = 'CtrlPMixed'

