"
" Plugins
"

call plug#begin('~/.vim/plugged')


"
" Additional functionality
"

Plug 'tpope/vim-dadbod'
Plug 'tpope/vim-dotenv'
Plug 'tpope/vim-commentary'

" Add more targets
Plug 'wellle/targets.vim'

" Tree view
Plug 'scrooloose/nerdtree'
Plug 'robinfehr/nerdtree-git-plugin'

" Better history
Plug 'mbbill/undotree'

" Fuzzy file finder
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Enable dot repetition for plugins
Plug 'tpope/vim-repeat'

" Surround blocks with characters
Plug 'tpope/vim-surround'

" Pairs of handy pairs mappings
" Good for moving lines and such
Plug 'tpope/vim-unimpaired'

" Git
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'airblade/vim-gitgutter'

" Save session
Plug 'tpope/vim-obsession'

" Word and case variants
Plug 'tpope/tpope-vim-abolish'

Plug 'metakirby5/codi.vim'

"
" Convenience
"

" Open files in last place
Plug 'farmergreg/vim-lastplace'

" Snippet engine
Plug 'SirVer/ultisnips'

" Emmet
Plug 'mattn/emmet-vim'

" Linting
Plug 'w0rp/ale'

Plug 'tranvansang/vim-close-pair'
" Plug 'Raimondi/delimitMate'

Plug 'Valloric/YouCompleteMe'

" Switch between single line and multi line statemnts
Plug 'AndrewRadev/splitjoin.vim'

" Spelling and grammar checking
Plug 'vim-scripts/LanguageTool'

Plug 'airblade/vim-accent'


"
" Inconvinience
"

Plug 'takac/vim-hardtime'


"
" Appearance
"

" Status bar
Plug 'vim-airline/vim-airline'

" Colourscheme
Plug 'dylanaraps/wal.vim'

" File icons
Plug 'ryanoasis/vim-devicons'

" Indent guides
Plug 'Yggdroot/indentLine'

" Automatically remove search highlighting
Plug 'haya14busa/incsearch.vim'

" Syntax plugins
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'mustache/vim-mustache-handlebars'
Plug 'digitaltoad/vim-pug'
Plug 'elzr/vim-json'
Plug 'plasticboy/vim-markdown'
Plug 'heavenshell/vim-jsdoc'
Plug 'lervag/vimtex'
Plug 'klen/python-mode'
Plug 'statico/vim-javascript-sql'
" Plug 'hdima/python-syntax'
" Plug 'nvie/vim-flake8'

call plug#end()


"
" Macros
"

" Macro to switch common.js to es6 imports
let @i = "^cwimportf=dwcwfrom lds("

" Macro to fix typos in line
let @s = "$[s1z="

" Convert class method to arrow function
let @a = "^f(i = f{i=> "


"
" General settings
"

" Use space as leader
let mapleader = " "

" Scroll with mousewheel
set mouse=a

filetype plugin indent on


"
" Appearance
"

" Syntax highlighting
syntax on

" Start scrolling 10 lines before the horizontal window border
set scrolloff=10

" Break on words not on characters
set formatoptions=l
set linebreak

" Show (certain) invisibles
set listchars=trail:·

" Indentation
set tabstop=2 softtabstop=2 expandtab shiftwidth=2 smarttab
set cinoptions=l1

" Line numbers
set number
set relativenumber

" Encoding and font
set encoding=utf-8
set guifont=Source\ Code\ Pro\ 12

map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>

let g:vim_markdown_conceal = 0

" Show trailing whitespace
match Todo /\s\+$/

" No folding
set nofoldenable

" Highlight characters that go over line length limit
augroup vimrc_autocmds
  autocmd BufEnter *.js highlight OverLength ctermbg=grey
  autocmd BufEnter *.js match OverLength /\%82v.*/
augroup END


"
" Navigation
"

" Quick pane cycling
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>


"
" Search
"

" Highlight results
set hlsearch

" Automatically hide results
let g:incsearch#auto_nohlsearch = 1
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
map n  <Plug>(incsearch-nohl-n)
map N  <Plug>(incsearch-nohl-N)
map *  <Plug>(incsearch-nohl-*)
map #  <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)

" Underline search results
let g:incsearch#highlight = {
\   'match' : {
\     'group' : 'IncSearchUnderline',
\     'priority' : '10'
\   },
\   'on_cursor' : {
\     'priority' : '100'
\   },
\   'cursor' : {
\     'group' : 'Search',
\     'priority' : '1000'
\   }
\ }

" Prefer case sensitive matches but allow both
set ignorecase
set smartcase
nnoremap <leader>/ :nohl<CR>


"
" Buffers
"

" Allow buffers in background
set hidden

" Go to nth buffer
let c = 1
while c <= 999
  execute "nnoremap " . c . "<leader> :" . c . "b\<CR>"
  let c += 1
endwhile

" Shortcut to close only current buffer
nnoremap <leader>q :bn<CR>:bd #<CR>

" Automatically update files
set autoread

function! Autoread(timer)
  silent checktime %
endfunction!
let timer = timer_start(100, 'Autoread', { 'repeat': -1 })


"
" Typing
"

function! RepeatChar(char, count)
  return repeat(a:char, a:count)
endfunction

" Empty line but don't delete it
nnoremap <leader>dd 0D

nnoremap s :<C-U>exec "normal i".RepeatChar(nr2char(getchar()), v:count1)<CR>
nnoremap S :<C-U>exec "normal a".RepeatChar(nr2char(getchar()), v:count1)<CR>

" Continue comments on next line when max length is reached
set textwidth=80
set formatoptions+=c


"
" Spelling
"

augroup spelling
  autocmd FileType markdown,gitcommit setlocal spell
augroup END

" Autocomplete words when spell is set
set complete+=kspell


""""""""""""""""""""""
"  Plugins settings  "
""""""""""""""""""""""


"
" Ale
"

nmap <silent> <leader>k <Plug>(ale_previous_wrap)
nmap <silent> <leader>j <Plug>(ale_next_wrap)

let g:ale_linters = {
\ 'cpp': [
\   'g++',
\ ],
\ 'jsx': [
\   'eslint',
\ ],
\}

let g:ale_fixers = {
\ 'javascript': [
\   'eslint',
\ ],
\}

let g:ale_python_flake8_options = "--ignore=W391"

nnoremap <leader>f :ALEFix<CR>


"
" You Complete Me
"

let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_filepath_blacklist = {}

let g:ycm_global_ycm_extra_conf = '/home/marcel/.vim/ycm_global_ycm_extra_conf.py'

let g:ycm_semantic_triggers = {
  \ 'css': [ 're!^\s{2}', 're!:\s+' ],
  \ }


"
" Filetype
"

let g:javascript_plugin_jsdoc = 1

"
" Airline
"

" Show by default
set laststatus=2

" Use powerline fonts
let g:airline_powerline_fonts = 1

" Supposed to make leaving insert mode faster
set ttimeoutlen=50

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" Hide things that are broken with my fonts or that I don't like the look of
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.linenr = ''

" Hide default status bar
set shortmess+=F

" Show tabline
let g:airline#extensions#tabline#enabled = 1

" Don't collapse filename
" let g:airline#extensions#tabline#fnamecollapse = 0

" Show buffer numbers in tabline
let g:airline#extensions#tabline#buffer_nr_show = 1

" Remove colon after buffer number
let g:airline#extensions#tabline#buffer_nr_format = '%s '



"
" NERDTree
"

augroup nerdstart
  " Automatically open when starting vim on directory
  autocmd StdinReadPre * let s:std_in=1
  autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

  " Close NERDTree if it's the only thing left
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
augroup END

" Keybinding to open NERDTree
nnoremap <leader>n :NERDTreeToggle<CR>

" Show hidden files
let NERDTreeShowHidden = 1

" Use colours not flags
let g:NERDTreeGitStatusNodeColorization = 1
let g:NERDTreeGitStatusWithFlags = 0

" Show files matching .gitignore
let g:NERDTreeShowIgnoredStatus = 1

" Files to be hidden
let NERDTreeIgnore = ['\.git$', '\.pioenvs$', '\.swp']

" Folders
let g:NERDTreeDirArrowExpandable = ''
let g:NERDTreeDirArrowCollapsible = ''
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsEnableFoldersOpenClose = 1

" Use pretty icons
let g:WebDevIconsNerdTreeAfterGlyphPadding = '  '

" Prevent brackets around icons when sourcing vimrc
if exists('g:loaded_webdevicons')
  call webdevicons#refresh()
endif


"
" Git gutter
"

let g:gitgutter_sign_added='┃'
let g:gitgutter_sign_modified='┃'
let g:gitgutter_sign_removed='◢'
let g:gitgutter_sign_removed_first_line='◥'
let g:gitgutter_sign_modified_removed='◢'


"
" FZF
"

nnoremap <C-p> :FZF<CR>


"
" Snippets
"

let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsSnippetsDir = '~/.vim/snippets'

let g:SuperTabDefaultCompletionType = '<C-n>'


"
" Wal
"

" Colourscheme settings
colorscheme wal


"
" Indent line
"

" Don't remove quotes from json
let g:vim_json_syntax_conceal = 0

" Enable leading spaces
let g:indentLine_leadingSpaceEnabled = 1
let g:indentLine_leadingSpaceChar = '·'

" Exclude NERDTree
let g:indentLine_bufNameExclude = ['_.*', 'NERD_tree.*']


"
" Emmet
"

let g:user_emmet_expandabbr_key = "<s-tab>"


"
" Commentary
"

let g:NERDSpaceDelims = 1

nmap <C-_> <Plug>CommentaryLine
vmap <C-_> <Plug>Commentary

let g:tex_conceal = ""

let g:languagetool_jar='/usr/share/java/languagetool/languagetool-commandline.jar'

let g:pymode_options_colorcolumn = 0
let g:pymode_folding = 0

function! CompletionChain(findstart, base)
  if a:findstart
    " Test against the functions one by one
    for func in g:user_completion_chain
      let pos = call(func, [a:findstart, a:base])
      " If a function can complete the prefix,
      " remember the name and return the result from the function
      if pos >= 0
        let s:current_completion = func
        return pos
      endif
    endfor

    " No completion can be done
    unlet! s:current_completion
    return -1
  elseif exists('s:current_completion')
    " Simply pass the arguments to the selected function
    return call(s:current_completion, [a:findstart, a:base])
  else
    return []
  endif
endfunction

let g:user_completion_chain = ['accent#AccentCompletion', 'youcompleteme#Complete']
set completefunc=CompletionChain

